A attempt to add missing changes to sysfs.h in backport
Originally based on commit https://github.com/aoleary/G4-Titan-Kernel/commit/63903f41176b16ccbaa3b4c2799fcbe8179a91d2

../fs/sysfs/file.c: In function ‘sysfs_add_file_mode_ns’:
../fs/sysfs/file.c:258:15: error: ‘SYSFS_PREALLOC’ undeclared (first use in this function); did you mean ‘SYSFS_MAGIC’?
    if (mode & SYSFS_PREALLOC)
               ^~~~~~~~~~~~~~
  CC      drivers/hid/hid-primax.o
  CC      drivers/regulator/helpers.o
               SYSFS_MAGIC
../fs/sysfs/file.c:258:15: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [../scripts/Makefile.build:257: fs/sysfs/file.o] Error 1
make[2]: *** [../scripts/Makefile.build:402: fs/sysfs] Error 2